version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - msa-public:/var/www/public:rw
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        env_file:
            - ./src/.env
        depends_on:
            - mysql
        restart: unless-stopped
        networks:
            - msa-network

    nginx:
        image: nginx:alpine
        volumes:
            - msa-public:/var/www/public:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        networks:
            - msa-network

    mysql:
        image: mariadb:10
        volumes:
            - msa-mysql:/var/lib/mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        env_file:
            - ./src/.env
        networks:
            - msa-network

networks:
    msa-network:

volumes:
    msa-public:
    msa-mysql:
